hoistPattern:
  - '*'
hoistedDependencies:
  /@esbuild/aix-ppc64/0.19.12:
    '@esbuild/aix-ppc64': private
  /@esbuild/android-arm/0.19.12:
    '@esbuild/android-arm': private
  /@esbuild/android-arm64/0.19.12:
    '@esbuild/android-arm64': private
  /@esbuild/android-x64/0.19.12:
    '@esbuild/android-x64': private
  /@esbuild/darwin-arm64/0.19.12:
    '@esbuild/darwin-arm64': private
  /@esbuild/darwin-x64/0.19.12:
    '@esbuild/darwin-x64': private
  /@esbuild/freebsd-arm64/0.19.12:
    '@esbuild/freebsd-arm64': private
  /@esbuild/freebsd-x64/0.19.12:
    '@esbuild/freebsd-x64': private
  /@esbuild/linux-arm/0.19.12:
    '@esbuild/linux-arm': private
  /@esbuild/linux-arm64/0.19.12:
    '@esbuild/linux-arm64': private
  /@esbuild/linux-ia32/0.19.12:
    '@esbuild/linux-ia32': private
  /@esbuild/linux-loong64/0.19.12:
    '@esbuild/linux-loong64': private
  /@esbuild/linux-mips64el/0.19.12:
    '@esbuild/linux-mips64el': private
  /@esbuild/linux-ppc64/0.19.12:
    '@esbuild/linux-ppc64': private
  /@esbuild/linux-riscv64/0.19.12:
    '@esbuild/linux-riscv64': private
  /@esbuild/linux-s390x/0.19.12:
    '@esbuild/linux-s390x': private
  /@esbuild/linux-x64/0.19.12:
    '@esbuild/linux-x64': private
  /@esbuild/netbsd-x64/0.19.12:
    '@esbuild/netbsd-x64': private
  /@esbuild/openbsd-x64/0.19.12:
    '@esbuild/openbsd-x64': private
  /@esbuild/sunos-x64/0.19.12:
    '@esbuild/sunos-x64': private
  /@esbuild/win32-arm64/0.19.12:
    '@esbuild/win32-arm64': private
  /@esbuild/win32-ia32/0.19.12:
    '@esbuild/win32-ia32': private
  /@esbuild/win32-x64/0.19.12:
    '@esbuild/win32-x64': private
  /@noble/hashes/1.4.0:
    '@noble/hashes': private
  /@noble/secp256k1/1.7.1:
    '@noble/secp256k1': private
  /@types/lodash/4.17.0:
    '@types/lodash': private
  /base-x/4.0.0:
    base-x: private
  /bip174/2.1.1:
    bip174: private
  /bs58/5.0.0:
    bs58: private
  /cipher-base/1.0.4:
    cipher-base: private
  /create-hash/1.2.0:
    create-hash: private
  /esbuild/0.19.12:
    esbuild: private
  /fsevents/2.3.3:
    fsevents: private
  /get-tsconfig/4.7.3:
    get-tsconfig: private
  /hash-base/3.1.0:
    hash-base: private
  /inherits/2.0.4:
    inherits: private
  /md5.js/1.3.5:
    md5.js: private
  /pvtsutils/1.3.5:
    pvtsutils: private
  /pvutils/1.1.3:
    pvutils: private
  /randombytes/2.1.0:
    randombytes: private
  /readable-stream/3.6.2:
    readable-stream: private
  /resolve-pkg-maps/1.0.0:
    resolve-pkg-maps: private
  /ripemd160/2.0.2:
    ripemd160: private
  /safe-buffer/5.2.1:
    safe-buffer: private
  /sha.js/2.4.11:
    sha.js: private
  /string_decoder/1.3.0:
    string_decoder: private
  /tslib/2.6.2:
    tslib: private
  /typeforce/1.18.0:
    typeforce: private
  /uint8array-tools/0.0.7:
    uint8array-tools: private
  /undici-types/5.26.5:
    undici-types: private
  /util-deprecate/1.0.2:
    util-deprecate: private
  /varuint-bitcoin/1.1.2:
    varuint-bitcoin: private
  /wif/2.0.6:
    wif: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@8.15.7
pendingBuilds: []
prunedAt: Thu, 09 May 2024 16:36:26 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: https://registry.npmjs.org/
skipped:
  - /@esbuild/aix-ppc64/0.19.12
  - /@esbuild/android-arm/0.19.12
  - /@esbuild/android-arm64/0.19.12
  - /@esbuild/android-x64/0.19.12
  - /@esbuild/darwin-arm64/0.19.12
  - /@esbuild/darwin-x64/0.19.12
  - /@esbuild/freebsd-arm64/0.19.12
  - /@esbuild/freebsd-x64/0.19.12
  - /@esbuild/linux-arm/0.19.12
  - /@esbuild/linux-arm64/0.19.12
  - /@esbuild/linux-ia32/0.19.12
  - /@esbuild/linux-loong64/0.19.12
  - /@esbuild/linux-mips64el/0.19.12
  - /@esbuild/linux-ppc64/0.19.12
  - /@esbuild/linux-riscv64/0.19.12
  - /@esbuild/linux-s390x/0.19.12
  - /@esbuild/linux-x64/0.19.12
  - /@esbuild/netbsd-x64/0.19.12
  - /@esbuild/openbsd-x64/0.19.12
  - /@esbuild/sunos-x64/0.19.12
  - /@esbuild/win32-arm64/0.19.12
  - /@esbuild/win32-ia32/0.19.12
  - /fsevents/2.3.3
storeDir: C:\Users\hugog\AppData\Local\pnpm\store\v3
virtualStoreDir: C:\Users\hugog\Desktop\summerofbitcoin\code-challenge-2024-Nesopie-main\code-challenge-2024-Nesopie-main\node_modules\.pnpm
